### ISSUE TITLE
commontool里一维向量的无穷范数返回本身还是绝对值？

### ISSUE THREAD

**Issue by ArtistArthur** [aofenghanyue/numericalAnalysisHomework#1]
-`template <typename T> T norm_inf(vector<T>& vec, int& index) {

	/*求向量无穷范数

	*输入向量，索引指针

	*输出无穷范数，其索引赋值给指针

	*/

	int len = vec.size();

	index = 0;

	if (len == 1) {

		return vec[0];

	}

	T max = vec[0];`
这个地方当len为1的时候你直接返回vec[0],是不是应该返回fabsvec[0]啊？
然后下面T max = vec[0];是否也应该改为 T max = fabs(vec[0]);？

**Comment by aofenghanyue** [comment]
这个地方可能注释没写清楚，这个函数求的是无穷范数对应的index和值，有时候需要知道无穷范数对应的是第几位(index)取到的，有时候(幂法)需要知道无穷范数对应的分量原本是正的还是负的，所以没有输出绝对值，而是直接输出的原值。

**Comment by ArtistArthur** [comment]
`for (int i = 1; i < len; i++) {

		if (fabs(vec[i]) > max) {

			max = fabs(vec[i]);

			index = i;

		}

	}

	return max;`
但是你后面求max的时候，返回的max实际上是绝对值吧，这个时候这两个返回值是不统一的，一个是原值一个是绝对值。
而且你定义了一个求符号的函数，需要知道符号的时候，直接调用一下这个函数就行了。
所以我还是绝对你这个地方有点问题，原因在于：你两种情况的返回值不统一，一个是返回vec[0],是原值，一个是max是绝对值。

**Comment by ArtistArthur** [comment]
另外我想问一下，这些代码都是你自己写的吗？我觉得写得好规范啊，是你写多了还是有参考模板？有参考模板的话请问可以提供一些吗？

**Comment by aofenghanyue** [comment]
em，这儿是有问题，谢谢指出，写作业的时候没有长度为一的数组所以没发现[捂脸]。
代码都是自己手撸的，因为学这门课之前我只会C和Python，老师不让用Python，我又嫌C太麻烦，花了一星期学的C++，所以写的比较僵硬，觉得代码规范是因为我之前python代码写多了，有习惯^_^

**Comment by ArtistArthur** [comment]
啊我哭了，我觉得你这个写得真的很好：
1、代码命名非常好，我一下就看懂了，风格也很好，我都在愁要用什么名字命名。
2、你把代码输出到文件里，可能是我写少了，我基本很少弄文件，看了你这个我才想起文件基本没怎么操作过，你输出的到代码的格式也很漂亮。
3、你居然只学一个星期就用模板并且还用得我觉得很漂亮，并且头文件也写得很规范，并且组织得也很好。
4、main文件和每个homework文件也弄得很好。
说实话我觉得你说一个星期学得能做成这样我感到很羞耻，可能是我太懒了。
另外请问你是大几的？是去年学的吗，我看你这是12月份传的，应该上完课是过了好久才传上来吧。

**Comment by aofenghanyue** [comment]
谢谢夸奖啦~
这是上学期吕淑娟老师的课，上完课后上传的，我都没想到有人会看，所以没写说明[哭笑]
命名全靠谷歌翻译...
实不相瞒我现在已经忘的差不多了，也就当时刚刚到b站看完c++的视频，外加复习完上课笔记趁热写的
其实写的过程很曲折，你看到的是最终版的，最开始是写在一个函数里，后来慢慢的重用代码多了就提取出来，这样慢慢写出来的。每次作业都要花一两天的时间做(coding5分钟，调试两小时)。
只是现在还对这代码的性能耿耿于怀，运行起来超级慢！！！调试发现是我写的数组类取值很慢，但是课上完了，就没继续研究了。

**Comment by ArtistArthur** [comment]
上学期，数值分析不是春季学期的课吗？秋季学期也有？
另外你说数组类取值很慢，是指用了vector吗？
用原生数组要好点吗？

**Comment by aofenghanyue** [comment]
我是研一的，我们的数值分析只在上个学期开(沙河)，我的homework1就是用原生数组的，也很慢，后面为了解决这个问题自己写的vector，但是速度并没有提升，问我计算机系的同学，他们说大概是因为我在不同的大数组中取值，导致缓存刷新吧啦吧啦，我也不懂。

**Comment by ArtistArthur** [comment]
哦哦，我也在沙河。没想到你们的数值分析居然和我们一样（作业也一样）

**Comment by aofenghanyue** [comment]
要不QQ(1772155440)聊吧，这上面聊感觉怪怪的，一条消息就是一封邮件...

**Comment by ArtistArthur** [comment]
好
